#!/bin/bash
if [[ ! -f ./Tshock.zip && "$*" == *-UpdateTshock* ]]; then echo "Downloading Tshock..." ; wget -qO - https://api.github.com/repos/Pryaxis/TShock/releases/latest | grep browser_download_url | grep TShock | cut -d  '"' -f 4 | wget -cqi - -O "Tshock.zip" && echo "Done!" ; echo "Unzipping...." ; unzip -u Tshock.zip && (echo "Unzipped Succesfully!" ; echo "Update Succesful! You can start the server now!" ; chmod a+x TerrariaServer.exe ; rm Tshock.zip) || (echo "Failed To Unzip!" ; rm Tshock.zip)
elif [[ -f ./Tshock.zip && "$*" == *-UpdateTshock* ]]; then echo "Unzipping already existing Zip file..." ; unzip -u Tshock.zip && (echo "Unzipped Succesfully! You can start the server now!" ; chmod a+x TerrariaServer.exe ; rm Tshock.zip) || (echo "Unzip Unsuccessful!" ; rm Tshock.zip)
fi

cd "`dirname "$0"`" ; chmod a+x TerrariaServer.exe ; (clear ; echo "Error: Please take out the update argument!" ; mono ./TerrariaServer.exe $@)

exit 0
